// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:23453518-0eb4-48cf-b460-fd2dab02a1f6",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_rZ2TH4VX5",
    "aws_user_pools_web_client_id": "6r66ulmr5c1k6ho1aag0hpohe7"
};


export default awsmobile;
